apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: # id on google cloud
  artifacts:
    - image: alibaba0010/auth:1
      context: server/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "server/auth/src/**/*.ts"
            dest: .
    - image: alibaba0010/client:1
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: alibaba0010/tickets
      context: server/tickets
      docker:
        dockerfile: Dockerfile
      # custom:
      #   buildCommand: bash -c "docker build -f server/tickets/Dockerfile --build-arg APP_DIR=../../server -t alibaba0010/tickets:a6d8f41-dirty ."
      # context: ./server/tickets
      sync:
        manual:
          - src: "server/tickets/src/**/*.ts"
            dest: .
    # - image: cygnetops/moderation-84 #3
    #   context: moderation
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "*.js"
    #         dest: .
    # - image: cygnetops/posts-95 #4
    #   context: posts
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "*.js"
    #         dest: .
    # - image: cygnetops/query-84 #5
    #   context: query
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "*.js"
    #         dest: .
# custom:
# buildCommand: bash -c "docker build -f server/auth/Dockerfile --build-arg APP_DIR=../../server -t alibaba0010/auth:a6d8f41-dirty ."
