apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: # id on google cloud
  artifacts:
    - image: alibaba0010/auth
      custom:
        buildCommand: bash -c "docker build -f server/auth/Dockerfile --build-arg APP_DIR=../../server -t alibaba0010/auth:da20ab3-dirty ."
      context: server/auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: alibaba0010/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: alibaba0010/tickets
      custom:
        buildCommand: bash -c "docker build -f server/tickets/Dockerfile --build-arg APP_DIR=../../server -t alibaba0010/tickets:da20ab3-dirty ."
      context: server/tickets
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: cygnetops/moderation-84 #3
    #   context: moderation
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "*.js"
    #         dest: .
    # - image: cygnetops/posts-95 #4
    #   context: posts
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "*.js"
    #         dest: .
    # - image: cygnetops/query-84 #5
    #   context: query
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "*.js"
    #         dest: .
